### ISSUE TITLE
How did you generate the wav FIR filters?

### ISSUE THREAD

**Issue by dumblob** [chadmed/asahi-audio#1]
I'd like to do something similar with my non-Apple laptop and would like to know your process of creation of those FIR filters. Thanks!

**Comment by chadmed** [comment]
I developed an EQ curve in Carla by ear for each driver, then transposed that over to an FIR in REW. I then exported those FIRs as 32-bit float WAVs. I confirmed that this EQ curve resulted in a fairly linear-sounding profile by then measuring the frequency response of the entire array, again using REW.

**Comment by dumblob** [comment]
Wow, thanks!

"by ear" means any specific patterns you've listened to? Also, did you compare it with some completely independent audio playing system (preferably some high fidelity system)?

I've played with REW 1.5 years ago on a high-fidelity system by my friend and was unable to find a good curve - what looked visually like a perfect curve sounded horrible.

Could you provide your REW profiles and all the tooling (scripts, configs, argument settings, etc.) if any?

**Comment by chadmed** [comment]
https://gist.github.com/chadmed/2c772c8fdac8280cb17846388203a213#file-experimental-testing

This gist is pretty much a step-by-step of what I did, including specs of the reference setup. Some of it has turned out to be wrong (the second set of woofers should not be used as subs for example), but the basic method is a good starting point. You can also ignore the asound.conf, it's wrong and will probably blow up your speakers.

I didn't actually use any specific REW profiles or configurations. The default setup was more than adequate for how I did this. I do intend to write up a SOP for doing this at some point, but I don't have the time for that right now.

**Comment by dumblob** [comment]
Thanks!

>I do intend to write up a SOP for doing this at some point, but I don't have the time for that right now.

Take your time.

I'll close this as you already clarified even my upcoming question whether you'll make an SOP part of this repo :wink:.
