### ISSUE TITLE
pipewire doesn't work after installing asahi-audio, but works after removing asahi-audio

### ISSUE THREAD

**Issue by blackxfiied** [chadmed/asahi-audio#10]
i've done all of the steps correctly?

**Comment by chadmed** [comment]
Have you enabled speakers in your devicetree and turned on the module parameter to enable them to be probed?

We are not enabling speakers by default at the moment because they are unsafe to use.

**Comment by rscaboyke** [comment]
If anyone just please would post all steps also the devicetree enabling speakers, one actually could try it outmvgCombassJean-Marie ***@***.******@***.***+32 485894441BE 0769.937.302IBAN BE58 3632 1574 1679Op 27 mei 2023 om 18:32 heeft James Calligeros ***@***.***> het volgende geschreven:﻿
Have you enabled speakers in your devicetree and turned on the module parameter to enable them to be probed?
We are not enabling speakers by default at the moment because they are unsafe to use.

**Comment by chadmed** [comment]
The decision to not post the steps is deliberate. None of this is ready for end users or even beta testers yet and we will
not facilitate the destruction of your laptop.

**Comment by rscaboyke** [comment]
Thanks for the info, but I read somewhere that if you follow the right steps on a MacBook M1 Pro 14 inch, it now was safe to use because of a safety deamon, but to try it out people should know how to edit device-tree and enable speakers, be free to correct me if I’m wrong.

Thx

mvg

Combass

Jean-Marie Bastiaens
Zaakvoerder
***@***.*** - ***@***.***
www.combass.be
+32 485894441
BE 0769.937.302
IBAN BE58 3632 1574 1679
